(function(){
  const C=APP_CONFIG,S=Store,E=STORY_EPISODES,root=document.querySelector('#app');let db=S.load(),route='home',review=[],reviewIndex=0,answerShown=false,storyFilter='ALL';
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
  function persist(){S.save(db)}
  function nav(){return `<nav class="bottom-nav" aria-label="メインメニュー">${[['home','⌂','ホーム'],['absorb','＋','吸収'],['release','↗','解放！'],['path','◇','君の道'],['stories','▤','物語']].map(x=>`<button data-route="${x[0]}" class="${route===x[0]?'active':''}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`}
  function shell(title,body,opts={}){root.innerHTML=`${title?`<header class="topbar">${opts.back?'<button class="back" data-route="'+opts.back+'" aria-label="戻る">←</button>':''}<h1>${title}</h1>${opts.action||''}</header>`:''}<main class="content">${body}</main>${opts.noNav?'':nav()}`;bindCommon()}
  function bindCommon(){root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.(b))}
  function go(r){route=r;window.scrollTo(0,0);render()}
  function render(){({home,absorb,release,path,stories,settings,reviewScreen:renderReview,storyReader:renderStory}[route]||home)()}
  function setup(){shell('',`<section class="setup"><div class="brand"><h1>覚えてるん♪</h1><p>～自分でつくる単語帳～</p><small>for 中学生</small></div><div class="setup-characters"><img src="たこぴー.png" alt="たこぴー"><img src="くらぴー.png" alt="くらぴー"></div><div class="panel"><h2>君の進む道を教えて！</h2><p class="muted">今わかることだけで大丈夫。学校や受験日は、あとから「君の道」に入れられます。</p><form id="setup-form"><label class="field"><span>現在の学年</span><select name="grade" required><option value="">選んでください</option><option>中1</option><option>中2</option><option>中3</option></select></label><label class="field"><span>現在の進路希望</span><select name="path" required><option value="">選んでください</option><option>まだ決まっていない</option><option>私立を考えている</option><option>公立を考えている</option><option>公立＋私立を考えている</option></select></label><button class="primary" type="submit">はじめる</button></form></div></section>`,{noNav:true});document.querySelector('#setup-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);db.user.grade=f.get('grade');db.user.path=f.get('path');db.setupComplete=true;persist();go('home')}}
  function dueCount(){return db.cards.filter(c=>!c.nextReview||c.nextReview<=S.localDate()).length}
  function nextExam(){const today=S.localDate();return db.exams.filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date))[0]}
  function finalExamStatus(){
    const date=db.user.finalExamDate;
    if(!date)return {state:'unset',message:'受験日が決まったら、ここに入れてって！',dateLabel:''};
    const remaining=S.dayDiff(S.localDate(),date),d=S.parseLocal(date);
    const dateLabel=`${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`;
    if(remaining===0)return {state:'today',message:'今日は受験の日',dateLabel};
    if(remaining<0)return {state:'complete',message:'ここまで歩いてきたね。',dateLabel};
    return {state:'upcoming',message:`受験まで あと${remaining}日`,dateLabel};
  }
  function finalExamCard(){const status=finalExamStatus();return `<div class="panel exam-goal ${status.state}"><span>最終受験予定日</span><h2>${esc(status.message)}</h2>${status.dateLabel?`<p>${esc(status.dateLabel)}</p>`:'<p class="muted">日付は下の「君の進む道」から、いつでも登録できます。</p>'}</div>`}
  function home(){const n=nextExam();shell('',`<section class="brand"><h1>覚えてるん♪</h1><p>～自分でつくる単語帳～</p><small>for 中学生</small></section><section class="home-actions"><button class="hero-action absorb" data-route="absorb"><div><strong>→ 吸収</strong><span>覚えたいことを吸い込むよ！</span></div><img src="たこぴー.png" alt="吸収担当のたこぴー"></button><button class="hero-action release" data-route="release"><div><strong>解放！</strong><span>習ったことを解き放つ！</span><small>${db.cards.length?`今日の復習候補 ${dueCount()}件`:'まずはカードを吸収しよう'}</small></div><img src="くらぴー.png" alt="解放担当のくらぴー"></button><div class="sub-actions"><button class="sub-action" data-route="path"><strong>◇ 君の道</strong><span>${n?`${esc(n.name)}まであと${Math.max(0,S.dayDiff(S.localDate(),n.date))}日`:'進路と試験の道標'}</span></button><button class="sub-action" data-route="stories"><strong>▤ ふたつの物語</strong><span>${db.stories.unlocked.length}話 解放済み</span></button></div></section><p class="daily-note">「怪しい」「記憶ゼロ」は失敗じゃない。見つけたら、また吸収すればいい。</p><button class="link-btn" data-route="settings">設定・データ管理</button>`)}
  function categories(subject){return [...(C.categories[subject]||['フリー']),...(db.customCategories[subject]||[])].filter((v,i,a)=>a.indexOf(v)===i)}
  function absorb(){const subject=C.subjects[0];shell('吸収する',`<div class="panel"><form id="card-form"><label class="field"><span>教科 <i class="req">必須</i></span><select name="subject" id="subject">${C.subjects.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field"><span>カテゴリ <i class="req">必須</i></span><div class="inline-actions"><select name="category" id="category">${categories(subject).map(x=>`<option>${x}</option>`).join('')}</select><button type="button" class="secondary" data-action="addCategory">追加</button></div></label><label class="field"><span>キーワード／問題 <i class="req">必須</i></span><textarea name="question" required placeholder="例：although の意味"></textarea></label><label class="field"><span>答え／自分なりの説明 <i class="req">必須</i></span><textarea name="answer" required placeholder="自分の言葉で書いてみよう"></textarea></label><fieldset class="field"><legend class="legend">習った時期</legend><div class="chips"><label class="chip"><input type="radio" name="periodType" value="current" checked><span>今の学年</span></label><label class="chip"><input type="radio" name="periodType" value="past"><span>これまでに習ったもの</span></label></div><select name="pastPeriod" id="past-period" hidden><option>不明</option><option>小学校</option><option>中1</option><option>中2</option><option>中3</option></select></fieldset><fieldset class="field"><legend class="legend">対象試験タグ（複数選択可）</legend><div class="chips">${C.examTags.map(x=>`<label class="chip"><input type="checkbox" name="tags" value="${x}"><span>${x}</span></label>`).join('')}</div></fieldset><button class="primary" type="submit">このカードを吸収する</button></form></div>`,{back:'home'});const sf=document.querySelector('#subject'),cat=document.querySelector('#category');sf.onchange=()=>cat.innerHTML=categories(sf.value).map(x=>`<option>${x}</option>`).join('');root.querySelectorAll('[name=periodType]').forEach(x=>x.onchange=()=>document.querySelector('#past-period').hidden=x.value!=='past'||!x.checked);document.querySelector('#card-form').onsubmit=saveCard}
  function saveCard(e){e.preventDefault();const f=new FormData(e.target),today=S.localDate();db.cards.push({id:id(),subject:f.get('subject'),category:f.get('category'),question:String(f.get('question')).trim(),answer:String(f.get('answer')).trim(),periodType:f.get('periodType'),period:f.get('periodType')==='past'?f.get('pastPeriod'):db.user.grade,tags:f.getAll('tags'),createdAt:today,nextReview:today,ratings:[]});markLearningDay();persist();toast('吸収できたよ。続けて入力できます');const subject=f.get('subject'),category=f.get('category');e.target.reset();e.target.subject.value=subject;document.querySelector('#category').innerHTML=categories(subject).map(x=>`<option ${x===category?'selected':''}>${x}</option>`).join('');document.querySelector('#past-period').hidden=true}
  function markLearningDay(){const today=S.localDate();if(db.learningDays.includes(today))return false;db.learningDays.push(today);unlockStory();return true}
  function unlockStory(){const lockedMain=E.filter(e=>e.type==='MAIN'&&!db.stories.unlocked.includes(e.episodeId));const lockedSide=E.filter(e=>e.type==='SIDE'&&!db.stories.unlocked.includes(e.episodeId));if(!lockedMain.length&&!lockedSide.length)return;let pick=null;if(db.user.finalExamDate&&db.user.finalExamDate<=S.localDate()){db.stories.unlocked=E.map(e=>e.episodeId);return}const elapsed=Math.max(1,S.dayDiff(db.createdAt,S.localDate())+1),total=db.user.finalExamDate?Math.max(1,S.dayDiff(db.createdAt,db.user.finalExamDate)):540,target=Math.min(180,Math.floor((elapsed/total)*180)+1),unlockedMain=db.stories.unlocked.filter(x=>x.startsWith('MAIN')).length;if(unlockedMain<target)pick=lockedMain[0];else pick=lockedSide[0]||lockedMain[0];if(pick)db.stories.unlocked.push(pick.episodeId)}
  function release(){shell('解放！',`<div class="panel" style="text-align:center"><img src="くらぴー.png" alt="くらぴー" width="100" height="100" style="object-fit:contain"><h2>今日はどれを解き放っちゃう？</h2><p class="muted">答えは自分で登録した言葉。採点ではなく、今の記憶を確かめます。</p></div><div class="option-list"><button class="choice" data-start="recommended">今日のおすすめ<span>予定日と最近の記憶状態から選ぶ</span></button><button class="choice" data-start="subject">教科から<span>教科とカテゴリを選ぶ</span></button><button class="choice" data-start="category">カテゴリから</button><button class="choice" data-start="tag">対象試験から</button><button class="choice" data-start="past">これまでに習ったもの</button><button class="choice" data-start="unsure">怪しいやつ</button><button class="choice" data-start="all">全部からおまかせ</button></div>`,{back:'home'});root.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>startChoice(b.dataset.start))}
  function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
  function startChoice(type){if(!db.cards.length){toast('先にカードを吸収しよう');return}if(type==='subject'||type==='category'||type==='tag'){renderPicker(type);return}let cards=[...db.cards],today=S.localDate();if(type==='recommended')cards.sort((a,b)=>score(b,today)-score(a,today));if(type==='past')cards=cards.filter(c=>c.periodType==='past');if(type==='unsure')cards=cards.filter(c=>['unsure','zero'].includes(c.ratings.at(-1)?.rating));if(type==='all')cards=shuffled(cards);begin(cards.slice(0,20))}
  function score(c,today){const last=c.ratings.at(-1)?.rating;return (c.nextReview<=today?100:0)+(['unsure','zero'].includes(last)?50:0)-S.dayDiff(c.createdAt,today)*.01}
  function renderPicker(type){let options=[];if(type==='subject')options=C.subjects;if(type==='category')options=[...new Set(db.cards.map(c=>c.category))];if(type==='tag')options=C.examTags;const label={subject:'教科',category:'カテゴリ',tag:'対象試験'}[type];shell(`${label}から選ぶ`,`<div class="panel"><div class="chips">${options.map(x=>`<button class="filter-chip" data-pick="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`,{back:'release'});root.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{let cards=db.cards.filter(c=>type==='tag'?c.tags.includes(b.dataset.pick):c[type]===b.dataset.pick);if(type==='subject'&&cards.length){renderSubjectCategory(b.dataset.pick);return}begin(shuffled(cards))})}
  function renderSubjectCategory(subject){
    const opts=['すべて',...new Set(db.cards.filter(c=>c.subject===subject).map(c=>c.category))];
    shell(`${subject}を解放`,`<div class="panel"><p class="muted">カテゴリを選べます。</p><div class="chips">${opts.map(x=>`<button class="filter-chip" data-cat="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`,{back:'release'});
    root.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>begin(shuffled(db.cards.filter(c=>c.subject===subject&&(b.dataset.cat==='すべて'||c.category===b.dataset.cat)))));
  }
  function begin(cards){if(!cards.length){toast('当てはまるカードはまだありません');return}review=cards;reviewIndex=0;answerShown=false;route='reviewScreen';render()}
  function renderReview(){const c=review[reviewIndex];if(!c){finishReview();return}shell('解放中',`<div class="progress"><i style="width:${reviewIndex/review.length*100}%"></i></div><div class="panel review-card"><span class="subject">${esc(c.subject)} ／ ${esc(c.category)}</span><h2>${esc(c.question)}</h2>${answerShown?`<div class="answer"><b>自分の答え</b><br>${esc(c.answer)}</div><p class="muted">今の記憶にいちばん近いものを選ぼう。</p><div class="ratings">${Object.entries(C.ratings).map(([k,v])=>`<button data-rate="${k}">${v.label}</button>`).join('')}</div>`:`<button class="primary blue" data-action="showAnswer">答えを見る</button>`}</div><button class="link-btn" data-action="finishReview">ここで終わる</button>`,{back:'release'});root.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>rate(b.dataset.rate))}
  function rate(rating){const c=review[reviewIndex],today=S.localDate();c.ratings.push({date:today,rating});c.nextReview=S.addDays(today,C.ratings[rating].days);markLearningDay();persist();if(['unsure','zero'].includes(rating))toast('そっか。じゃあ、また出すね。');reviewIndex++;answerShown=false;render()}
  function finishReview(){go('release');toast('今日の解放、おつかれさま')}
  function path(){const n=nextExam();shell('君の道',`${finalExamCard()}${n?`<div class="panel milestone"><span>次の道標</span><h2>${esc(n.name)}まであと${Math.max(0,S.dayDiff(S.localDate(),n.date))}日</h2><p class="muted">${esc(n.type)} ・ ${esc(n.date)}</p></div>`:''}<div class="panel"><h2>君の進む道</h2><form id="path-form"><div class="grid-2"><label class="field"><span>現在の学年</span><select name="grade">${['中1','中2','中3'].map(x=>`<option ${db.user.grade===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="field"><span>進路希望</span><select name="path">${['まだ決まっていない','私立を考えている','公立を考えている','公立＋私立を考えている'].map(x=>`<option ${db.user.path===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label class="field"><span>志望校</span><input name="school" value="${esc(db.user.school)}" placeholder="決まってからで大丈夫"></label><label class="field"><span>最終受験予定日</span><input type="date" name="finalExamDate" value="${esc(db.user.finalExamDate)}"></label><label class="field"><span>メモ</span><textarea name="memo">${esc(db.user.memo)}</textarea></label><button class="primary" type="submit">君の道を保存</button></form></div><div class="section-title"><h2>試験予定</h2><span class="count">${db.exams.length}件</span></div><div class="panel"><form id="exam-form"><label class="field"><span>名称</span><input name="name" required placeholder="例：2学期中間"></label><div class="grid-2"><label class="field"><span>種類</span><select name="type">${['定期テスト','実力テスト','模試','入試','その他'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field"><span>日付</span><input type="date" name="date" required></label></div><label class="field"><span>メモ</span><input name="memo"></label><button class="secondary" type="submit">試験予定を追加</button></form></div><div class="panel">${db.exams.length?db.exams.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<div class="exam-item"><span class="date-badge">${esc(x.date.slice(5).replace('-','/'))}</span><div style="flex:1"><b>${esc(x.name)}</b><div class="muted">${esc(x.type)}${x.memo?' ・ '+esc(x.memo):''}</div></div><button class="icon-btn" data-delete-exam="${x.id}" aria-label="削除">×</button></div>`).join(''):'<div class="empty">試験予定はまだありません</div>'}</div>`,{back:'home'});document.querySelector('#path-form').onsubmit=e=>{e.preventDefault();Object.assign(db.user,Object.fromEntries(new FormData(e.target)));persist();toast('君の道を保存しました');render()};document.querySelector('#exam-form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));db.exams.push({id:id(),...f});persist();toast('試験予定を追加しました');render()};root.querySelectorAll('[data-delete-exam]').forEach(b=>b.onclick=()=>{if(confirm('この試験予定を削除しますか？')){db.exams=db.exams.filter(x=>x.id!==b.dataset.deleteExam);persist();render()}})}
  function stories(){
    const unlocked=E.filter(e=>db.stories.unlocked.includes(e.episodeId));
    const visible=unlocked.filter(e=>storyFilter==='ALL'||e.type===storyFilter);
    const list=visible.length?visible.map(e=>{const read=db.stories.read.includes(e.episodeId);return `<div class="story-item"><span>◈</span><button data-story="${e.episodeId}"><span class="story-type">${esc(e.chapter)}</span><b>${esc(e.title)}</b></button>${!read?'<i class="unread"></i>':''}</div>`}).join(''):'<div class="empty">この棚には、まだ取り戻した記憶がありません</div>';
    shell('ふたつの物語',`<div class="panel"><h2>むかしのきおく</h2><p class="muted">意味のある「吸収」か「解放」をした日に、最大1話が解放されます。休んだ日があっても、何も失いません。</p><b>これまでに取り戻した記憶：${unlocked.length}話</b></div><div class="chips" style="margin-bottom:14px">${[['ALL','すべて'],['MAIN','MAIN'],['SIDE','SIDE']].map(x=>`<button class="filter-chip ${storyFilter===x[0]?'selected':''}" data-story-filter="${x[0]}">${x[1]}</button>`).join('')}</div><div class="panel">${list}</div>`,{back:'home'});
    root.querySelectorAll('[data-story-filter]').forEach(b=>b.onclick=()=>{storyFilter=b.dataset.storyFilter;stories()});
    root.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{sessionStorage.setItem('storyId',b.dataset.story);go('storyReader')});
  }
  function renderStory(){const e=E.find(x=>x.episodeId===sessionStorage.getItem('storyId'));if(!e||!db.stories.unlocked.includes(e.episodeId)){go('stories');return}if(!db.stories.read.includes(e.episodeId)){db.stories.read.push(e.episodeId);persist()}shell(e.title,`<div class="panel"><span class="story-type">${esc(e.chapter)}</span><h2>${esc(e.title)}</h2><p class="muted">${esc(e.character)}</p><div class="story-body">${esc(e.body)}</div></div>`,{back:'stories'})}
  function settings(){shell('設定・データ管理',`<div class="panel"><h2>データ管理</h2><div class="settings-row"><b>データを書き出す</b><p class="muted">カード、復習履歴、君の道、物語の進み具合をJSONで保存します。</p><button class="secondary" data-action="exportData">データを書き出す</button></div><div class="settings-row"><b>データを読み込む</b><p class="muted">このアプリから書き出したJSONを読み込みます。現在のデータは置き換わります。</p><button class="secondary" data-action="importData">データを読み込む</button></div><div class="settings-row"><b>すべてのデータを消去</b><p class="muted">この端末に保存された内容を初期化します。</p><button class="danger" data-action="resetData">すべて消去する</button></div></div><p class="version">覚えてるん♪ v0.1 ・ schema ${db.schemaVersion}</p>`,{back:'home'})}
  const actions={showAnswer(){answerShown=true;render()},finishReview,addCategory(){const subject=document.querySelector('#subject').value,name=prompt(`${subject}の新しいカテゴリ名を入力してください`);if(!name?.trim())return;db.customCategories[subject]??=[];if(!db.customCategories[subject].includes(name.trim()))db.customCategories[subject].push(name.trim());persist();document.querySelector('#category').innerHTML=categories(subject).map(x=>`<option ${x===name.trim()?'selected':''}>${esc(x)}</option>`).join('');toast('カテゴリを追加しました')},exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`oboeterun-backup-${S.localDate()}.json`;a.click();URL.revokeObjectURL(a.href);toast('データを書き出しました')},importData(){document.querySelector('#import-file').click()},resetData(){if(confirm('すべてのデータを消去します。元に戻せません。よろしいですか？')){localStorage.removeItem(C.storageKey);db=S.fresh();setup()}}};
  document.querySelector('#import-file').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!S.validImport(data))throw new Error();if(confirm('現在のデータを読み込んだ内容に置き換えますか？')){db=S.normalize(data);persist();go('home');toast('データを読み込みました')}}catch(err){alert('読み込めないデータです。覚えてるん♪のバックアップファイルを選んでください。')}e.target.value=''};reader.readAsText(file)};
  if(!db.setupComplete)setup();else render();
})();
